### ISSUE TITLE
Onvif or rtsp > go2rtc >windows virtual webcam for OBS/vmix etc

### ISSUE THREAD

**Issue by d-stocker** [AlexxIT/Blog#12]
Am in well over my head, but go2rtc seems like a swiss-army knife of video.
If its possible, how would I configure go2rtc to in order to use an IP Camera as a webcam on windows?
Am running go2rtc on Home Assistant.

Thanks
DS

**Comment by pbvdven** [comment]
U can use software like manycam that can use rtsp stream as webcam in windows.

**Comment by AlexxIT** [comment]
Wrong repository

**Comment by felipecrs** [comment]
You can use OBS Studio too with the virtual camera.
