### ISSUE TITLE
Version 2024.1.2 causes integration issues with SONOFF devices

### ISSUE THREAD

**Issue by Avishaham** [AlexxIT/Blog#18]
After installing the 2024.1.2 core update, SONOFF integration issues occurred. 
HA did not recognize entities status changes, toggle service calls only went one way -> to ON and not OFF, probably because to the status recognition issues.
After downgrading to core version 2023.12.1 problem solved.

**Comment by Avishaham** [comment]
So, we'll have to stick to Core 2023.12.1 ?

**Comment by andrewjswan** [comment]
> So, we'll have to stick to Core 2023.12.1 ?

This is a blog, only the author writes here, open the issue in the integration repository (if it is not already open). :)
