### ISSUE TITLE
Chinese WLAN camera

### ISSUE THREAD

**Issue by littlefico** [AlexxIT/Blog#25]
Hi Alex, really appreciate your work here. I'm very interested in techy stuff but am away from coding like from here to the moon. 

I bought some cooau cams at Amazon just to watch my dog outside the house. 
I cannot get a stream on vlc or ispy. I paired it with an app called cloudedge and there I have a stream after connecting via qr code.

1 Should I reset the device before trying to connect with your software? 
2 is it possible to see the stream on the app and on my PC (windows 10)?
3 is there any chance this won't work with this particular camera?

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/Blog
