### ISSUE TITLE
Recent Sonoff Integration Issues

### ISSUE THREAD

**Issue by davel4wa** [AlexxIT/Blog#4]
My HA installation is receiving a persistent notification to reconfigure the Sonoff integration. The log shows that the password is incorrect. I have verified the account password in eWeLink and changed it in both the eWeLink app and in HA. 
There is also this error in the log on restart of HA:

Logger: homeassistant.components.number
Source: components/number/__init__.py:220
Integration: Number (documentation, issues)
First occurred: 9:39:12 AM (3 occurrences)
Last logged: 9:39:12 AM

custom_components.sonoff.number::XNumber is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom component author.
custom_components.sonoff.number::XPulseWidth is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom component author.

**Comment by AlexxIT** [comment]
You shouldn't create issues in this repo
