### ISSUE TITLE
error="x509: certificate is valid for 127.0.0.1, fe80::1, not 172.16.82.2"

### ISSUE THREAD

**Issue by wjnelson78** [AlexxIT/Blog#6]
Is there the ability to ignore ssl certificate valid status?
I was tinkering around with HASS today and part of the tinkering brought this into the mix.  172.16.72.2 is the internal IP for my Unifi NVR

02:07:56.693 INF go2rtc version 0.1-rc.5 linux/amd64
02:07:56.693 INF [api] listen addr=:1984
02:07:56.695 INF [rtsp] listen addr=:8554
02:07:56.697 INF [hass] load stream url="hass:Scrypted D094"
02:07:56.697 INF [srtp] listen addr=:8443
02:17:13.578 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:51 > error="x509: certificate is valid for 127.0.0.1, fe80::1, not 172.16.82.2"
02:17:13.587 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:51 > error="x509: certificate is valid for 127.0.0.1, fe80::1, not 172.16.82.2"
02:17:13.587 WRN github.com/AlexxIT/go2rtc/cmd/webrtc/webrtc.go:197 > stream.AddConsumer error="sources unavailable: 1"
02:17:13.588 ERR [api.hass] exchange SDP error="sources unavailable: 1"

**Comment by AlexxIT** [comment]
You shouldn't create issues here
